
project_id = "pwnjzbluumgokkuiustn"

[functions.update-stock-prices]
verify_jwt = false

[functions.portfolio-chat]
verify_jwt = true

[functions.get-stock-data]
verify_jwt = false

[functions.get-secret]
verify_jwt = false
