// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwnjzbluumgokkuiustn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3bmp6Ymx1dW1nb2trdWl1c3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Nzc3NjAsImV4cCI6MjA1NTU1Mzc2MH0.oJokrIM911gc7wwdNxe8Xt0TwZfF5IMyQ_asMM983NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);